### ISSUE TITLE
How Does 5.2 load() Work?

### ISSUE THREAD

**Issue by CannibalVox** [moonjit/moonjit#113]
Hello,

I was recently delighted to see that moonjit supports load(string, chunkname, [mode, [env]]), which will really come in handy for my project.  However, it does not seem to support _ENV.  That's fine, but where does the env table's contents end up when I run the loaded script?  Is it _G?

**Comment by siddhesh** [comment]
Have you tried getfenv/setfenv? _ENV is a replacement for that function pair and luajit decided against that change.

**Comment by CannibalVox** [comment]
The moonjit documentation indicates that it does support it, in some form.  So I'm wondering what form that support takes.

**Comment by siddhesh** [comment]
Instead of the single _ENV, you make your own environment table using getfenv().

So in short form, instead of using _ENV in `load(string, chunkname, mode, _ENV)` you'd do `load(string, chunkname, mode, getfenv())`.  You probably want to do something useful with the environment, so you'd probably need something like this instead:

```
env = getfenv()
env['BAR'] = 'foo'
foo, err = load(string, chunkname, mode, env)
...
```

**Comment by CannibalVox** [comment]
I'm asking where `BAR` would be located when running the code in string.  Is it on `_G`?

**Comment by siddhesh** [comment]
Yes, in `_G` and in the environment returned by `getfenv()` in the callee.
