### ISSUE TITLE
Does moonjit support Windows/x86 exceptions?

### ISSUE THREAD

**Issue by iamtimmy** [moonjit/moonjit#130]
I'm aware that the documentation states that it doesn't but if you look here:
https://repo.or.cz/w/luajit-2.0.git/blob_plain/v2.1:/doc/extensions.html

and scroll down to the bottom you'll find that the 2.1 branch actually has full support for exceptions.

Since I see that this repo has the commits from Mike Pall still, you'd think it has the support.

**Comment by iamtimmy** [comment]
I should clarify that I mean Windows/x86 exceptions. Sorry.

**Comment by siddhesh** [comment]
Yes, it looks like a documentation bug.  moonjit is still more or less the same as LuaJIT when it comes to core functionality, so you should have C++ exception interoperability on Windows/x86.  I haven't verified this though, since I do not have access to Windows/x86 systems and am personally disinclined to work on Windows.
