### ISSUE TITLE
47bit lightuserdata limitation

### ISSUE THREAD

**Issue by rhenwood-arm** [moonjit/moonjit#132]
hi All,

I am not active in this excellent project, but I've come across some instances of the 47bit limitation in down-stream projects. I recognize this is a known, long-standing issue and there is plenty of desire to fix, but little time and resource to dedicate to it. My goal in opening this issue to track instances in the Lua ecosystem where other projects are feeling the impact.

So far, I've seen:
https://github.com/wahern/cqueues/issues/241#issuecomment-668159587
https://github.com/wahern/luaossl/pull/173

**Comment by vcunat** [comment]
I'd probably reference mainly https://github.com/LuaJIT/LuaJIT/issues/49  (though there have been multiple relevant issues and PRs in that repo)

**Comment by fsfod** [comment]
I saw Kong worked around it by splitting the address space that lightuserdata could represent https://github.com/Kong/openresty-patches/pull/47

**Comment by vcunat** [comment]
Oh right, I forgot that reference.  Note that there's a system where that vanilla approach didn't work, so it's not 100% either: https://github.com/Kong/openresty-patches/pull/49#issuecomment-539248469

**Comment by siddhesh** [comment]
Perhaps lightuserdata pointers could be split into page+offset (or HI47+LO17 to get the full 64-bit range) in adjacent GC slots, similar in concept to how strings are stored.  It will not solve the performance issue due to double syscalls for GC objects, but it ought to at least solve the lightud problem.

We could probably do this to all GC references, but at that point we may as well consider rewriting all of GC and the type identification system.  At which point, the interpreter should be rewritten in C too so that it's not such a pain to update it.

**Comment by waruqi** [comment]
There is also a solution here.

https://github.com/xmake-io/xmake/blob/96b0eae26058482a83f5bbf57bab15a834339464/core/src/xmake/prefix.h#L45-L82

**Comment by fsfod** [comment]
I don't know if i should be horrified or amazed at using Lua string interning to get unique values, but i guess if you don't have many different lightuserdata values it won't slow down the GC. You could also just use the raw bytes of the pointer as the string since Lua strings can contain null values in the middle.

**Comment by waruqi** [comment]
> I don't know if i should be horrified or amazed at using Lua string interning to get unique values, but i guess if you don't have many different lightuserdata values it won't slow down the GC. You could also just use the raw bytes of the pointer as the string since Lua strings can contain null values in the middle.

It works fine for me and I will not use too many lightuserdata pointers. 

And for pointer values that do not exceed 47bits, I will still try to directly use the lua_pushlightuserdata interface, which will not affect too much performance.

**Comment by vcunat** [comment]
This should be resolved upstream now: https://github.com/LuaJIT/LuaJIT/commit/e9af1abec54
