### ISSUE TITLE
Should this repo do releases?

### ISSUE THREAD

**Issue by daurnimator** [moonjit/moonjit#15]
I'm considering if I should try and package your luajit fork as the default in Arch Linux; this would essentially be blessing this repository as the new upstream.
  - Do you think this is a good idea?
  - What do you think about doing releases?

**Comment by siddhesh** [comment]
Hi @daurnimator !

So basically what I'm doing in Fedora is to make patches on top of the original repo, which is quickly getting out of hand, especially as I add 5.2/5.3 support.  I would like to do releases, but as the first option I am trying to get the openresty luajit2 fork to be the officially blessed repo (and help with development *and* release tarballs there instead) since that would mean a clean break from the original project with a new name and hence a new package luajit2 that obsoletes LuaJIT.  See https://github.com/openresty/luajit2/issues/80

Does this approach work for you on Arch?

**Comment by daurnimator** [comment]
I don't see openresty's fork as suitable: they [add new APIs](https://github.com/openresty/luajit2#openresty-extensions) that I consider breaking and unsuitable for a general LuaJIT package.

**Comment by siddhesh** [comment]
Agreed, there are some extensions (such as `table.*`) that may conflict with future lua API but there's also `jit.*` and `thread.*` that don't really have anything to do with lua and are valuable addons.  I have incorporated those into my repo and was thinking of putting the rest (i.e. `table.*`) behind a configure flag that enables it only for OpenResty builds.

Maybe the pragmatic quick way would be to not block on openresty/luajit2 and just go with package releases from this repo.  I'll continue working towards reducing the delta with openresty/luajit2 but that could be an independent issue.

Do you have a preference for siddhesh/LuaJIT vs siddhesh/luajit2, i.e. would it be cleaner for you to just update the source tarball of an existing package in Arch or make a new package luajit2 that obsoletes LuaJIT?  I think for Fedora the latter would be cleaner, i.e. keep LuaJIT at 2.1 forever and create a new package luajit2 that obsoletes LuaJIT.  That way the LuaJIT package tracks the v2.1 branch here and remains backward compatible with LuaJIT/LuaJIT and we can start making progress with siddhesh/LuaJIT.

Also, maybe it should be luajit2/luajit2 so that we can make a proper group that is not associated with my identity.  I could get hit by a bus, etc.

**Comment by daurnimator** [comment]
> also `jit.*` and `thread.*` that don't really have anything to do with lua and are valuable addons.

I think `jit` is fine: that namespace is already claimed by Mike Pall's LuaJIT. However `thread.exdata` I'm less excited about.

> the rest (i.e. `table.*`) behind a configure flag that enables it only for OpenResty builds.

Please do.



> Do you have a preference for siddhesh/LuaJIT vs siddhesh/luajit2

nope.



> update the source tarball of an existing package in Arch or make a new package luajit2 that obsoletes LuaJIT?

I'd update the existing package to use your release. "luajit2" is far too confusing as a name.
If I was you I'd release as "LuaJIT 2.2" or similar.

**Comment by siddhesh** [comment]
I started a conversation for this on the [luajit mailing list](https://www.freelists.org/post/luajit/Regular-releases-for-luajit-from-the-new-repo-and-future-roadmap) and it's taken a different turn, with many people preferring that I call the project something else altogether and make it a hard fork instead of attempting to continue in the same name.  It is definitely a more disappointing conclusion because I have been trying to avoid a hard fork, but such is life I guess.

So it's going to have to be a new package called lunarjit or bananajit or whatever.  Naming things is my least favourite programming task.

**Comment by daurnimator** [comment]
Picking a different name to me implies that you *don't* intend to be the new upstream but are instead are forking the project for your own goals: I would not package such a project as a replacement for LuaJIT in general distro repositories.

**Comment by siddhesh** [comment]
Right, it won't be a drop in replacement.  In any case, here's how I have concluded that conversation: I'm going to wait two weeks for Mike to object to my usage of the `LuaJIT` name to do releases and if he doesn't, I'll upload the first release tarballs here; v2.1.1 off the v2.1 branch and v2.2 off the master branch.

**Comment by siddhesh** [comment]
The conversation around naming got a bit crazy so I have given up on it.  I have renamed the repository and project to moonjit.  I'll fix up and do releases over the next couple of weeks.  Sorry this is not quite what Arch needed or for that matter other distributions, but it seems like the best alternative to keep hacking at luajit and not draw the ire of those who feel emotionally connected to the name.

Please let me know if there's any way in which I can help make it easier for Arch to package moonjit as an alternative or replacement for luajit.

**Comment by ThePhD** [comment]
For what it's worth, I would have preferred you took over and updated LuaJIT permanently. I spend a lot of my time dealing with people bringing me outdated LuaJIT/Lua/{CustomMinorSpinoffName} versions, and it would've been great to just tell them to "update" rather than "get the new moonjit distribution".

Alas. I hope this blossoms and becomes the new de-facto LuaJIT.

**Comment by aryajur** [comment]
I agree that it would have been much better if it would have been LuaJIT. By not being open for anyone to take charge to continue LuaJIT update/maintainence they are just declaring it dead and cause more fragmentation. 
To make it a standard JIT for Lua would recommend coming up with a set of baseline aims to which everyone can depend upon. One of them could be to be compatible with PUC Lua versions. I don't think any JIT carries on with that aim.

**Comment by vcunat** [comment]
Looking at push activity in the official repo and other signals, I believe distros will need to eventually start using some drop-in replacement, and in that case it seems highly desirable to **keep the name** (EDIT: "LuaJIT", to be clear).

To reduce the confusion, you could also **tweak the versioning**, e.g. start releasing as v2.2 so that everywhere it's easily visible whose version they have &ndash; and perhaps even separate the compat-risky changes to a 2.3 branch in case you didn't feel like hiding them (e.g. behind a configuration flag).  On a quick look I can't see these requiring lots of porting work for luajit users, but a drop-in replacement will certainly be useful.

**Comment by siddhesh** [comment]
> Looking at push activity in the official repo and other signals, I believe distros will need to eventually start using some drop-in replacement, and in that case it seems highly desirable to **keep the name** (EDIT: "LuaJIT", to be clear).
> 
From my discussions with other distribution vendors (I co-maintain the Fedora package) they'll work around the rename in one of two ways, either by just changing the upstream source and keeping the package name the same (there's precedent for this with eglibc on Debian) or make a new package that Obsoletes/Provides luajit.

> To reduce the confusion, you could also **tweak the versioning**, e.g. start releasing as v2.2 so that everywhere it's easily visible whose version they have – and perhaps even separate the compat-risky changes to a 2.3 branch in case you didn't feel like hiding them (e.g. behind a configuration flag). On a quick look I can't see these requiring lots of porting work for luajit users, but a drop-in replacement will certainly be useful.

Yes, the release off master will be 2.2.x and off v2.1 will be 2.1.1, etc.  The primary goal for the v2.1 branch will be to remain compatible with v2.1 on LuaJIT/LuaJIT, so no new 5.x features there.  There could be a case for new architecture ports though as long as they don't leak in incompatible features.

**Comment by siddhesh** [comment]
A comment on the status for a release.  I'm thinking of the following key tasks to be completed before cutting a release:

1. CI integration for PRs.  Azure pipelines integration is already underway thanks to #18 and I'd like to get Travis done on similar lines to get more architectures supported.  I'll reach out to people to get s390x in too.
2. Updates to documentation and README, CONTRIBUTORS, etc to reflect the fact that this is a new fork that has nothing to do with LuaJIT and yet, aims to continue development.
3. Bug fixes and a final check to ensure we don't end up releasing any breaking features.  I'd like to believe I've been careful but hey, I've also [defined TWO incorrectly](https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=dd930cc57100377d02a45b9113d6a3dc93136cbc) in the past ;)

Anything else that anybody can think of that needs to be fixed before a release goes out?  This first one doesn't have to be perfect but it definitely shouldn't break things for existing luajit users who may want to try out moonjit.

**Comment by siddhesh** [comment]
I've done the v2.2.1 release, which should have a number of bug fixes and architecture enablement for those stuck on 2.1.0-beta3.  You can download tarballs here:

https://github.com/moonjit/moonjit/releases/tag/2.1.1

I have updated documentation to reflect the fact that this is not the LuaJIT project, but the binaries and other artifacts themselves remain the same and can be a drop-in replacement for LuaJIT-2.1.0-beta3.

I'll do a 2.2 release, hopefully by this weekend.

**Comment by ExtReMLapin** [comment]
We really need some kind of changelogs (with details), right now, we don't know what changes since LuaJIT 2.1.0-beta3 unless we read the commit messages one by one.

**Comment by siddhesh** [comment]
Got it.  2.1.1 is kinda broken thanks to me missing a couple of places to update the version number so I'll have to do a 2.1.2 this weekend.  I'll write a more detailed changelog in that release note (i.e. 2.1.0-beta3..2.1.2) and also for 2.2.0.

**Comment by XVilka** [comment]
Can be closed now I guess, with https://github.com/moonjit/moonjit/releases/tag/2.2.0 released?
