### ISSUE TITLE
change build system?

### ISSUE THREAD

**Issue by joe-92** [moonjit/moonjit#22]
I'd like to ask what is the general opinion about changing the build system, for example to CMake or Meson?
This would possibly have the following advantages:

- There is only one build system for Linux, Windows, BSD, Android, ... which has to be maintained
- Currently the msvcbuild.bat script is limited; another build system would allow to support more different options (e.g. LUAJIT_ENABLE_GC64, LUAJIT_DISABLE_FFI, LUAJIT_ENABLE_LUA52COMPAT)
- Possibly easier testing across various define combinations?

What do you think? There are already various CMake (e.g. https://github.com/WohlSoft/LuaJIT resp. https://github.com/LuoJinghua/LuaJIT/tree/v2.1) or Meson (e.g. https://github.com/franko/luajit) build scripts which could be adopted.

**Comment by MageSlayer** [comment]
Personally I vote against any additional build systems.

Those build system are larger/more complex than LuaJIT entire codebase.
And they behave strange sometimes by itself. 

cmake devs like to break things from version to version.
meson requires another(!!!) interpreter to be present.

Mike did a great job of keeping build complexity at minimum. Please do the same.

**Comment by hippi777** [comment]
hi there! :)

i think that _additional_ build systems can be fine as far as they won't increase the complexity of the current codebase/build system with more than like a dozen of lines that wouldn't affect maintainability for those who just doesn't care about them... then who is interested in using them will use and maintain them, while others won't feel it as a downside... otoh, most likely i would be against _switching_ to other build systems, but hey, i dunno so many of them! i think its still better to have them under the same flagship instead of having forks/patches only for this reason...

[the not so important part]
btw i even wonder about a lua based build system, lua is cool and probably needs no much extras to be able to make it happen, as even gnu make is kinda bloated to me, but anyhow the show must be started from somewhere... ive got currently a bash file for bootstrapping, like collect sauces, install any necessary missing sys deps and tools necessary, and start my app, cuz gnu make isn't installed by default on a fresh debian, but bash is there (and i even wonder about dash compatibility that i havent even test so far now; and about how to leave that out from the game, maybe debian also has whatever version of lua on a fresh install, and anyhow, we can't really make new binaries without already having some, so the game is kinda trust based anyhow, even with lfs, gentoo etc)
[/the not so important part]

all the bests, and have fun! :)

**Comment by siddhesh** [comment]
> Those build system are larger/more complex than LuaJIT entire codebase.

This is my current opinion too, the current makefile seems to do what's needed for moonjit.  There is scope for improvement (evaluating LTO vs `make amalg` for example) but I can't think of a motivating use case to add more layers.

I requested an issue to be created because I'm curious to know what kind of use cases are not satisfied by the Makefile approach, or need jumping through hoops that additional tooling would fix.

Unifying builds across platforms could be a motivating reason.  I'll be happy to evaluate PRs to see how much complexity it adds and if it's worth the effort.

> And they behave strange sometimes by itself.
> 
> cmake devs like to break things from version to version.
> meson requires another(!!!) interpreter to be present.

Requiring python seems like a reasonable reason to keep meson out of contention.

**Comment by fsfod** [comment]
The windows build bat file does feel incredibly limited in options compared to the makefile but i think built-in alternatives are mostly limited the [make](https://docs.microsoft.com/en-us/cpp/build/reference/nmake-reference?view=vs-2019) [clone](https://devblogs.microsoft.com/oldnewthing/20190325-00/?p=102359) in MSVC.

One huge pet peeve I have the with current build setup though is all the generated headers and object files are placed in the same directory as source randomly breaking the build when building both Linux and Windows from the same repo.

**Comment by ghost** [comment]
How about tup？？
http://gittup.org/tup/

**Comment by siddhesh** [comment]
> The windows build bat file does feel incredibly limited in options compared to the makefile but i think built-in alternatives are mostly limited the [make](https://docs.microsoft.com/en-us/cpp/build/reference/nmake-reference?view=vs-2019) [clone](https://devblogs.microsoft.com/oldnewthing/20190325-00/?p=102359) in MSVC.
> 

Something like cmake assumes the presence of make/nmake, so it won't actually solve this problem.  Am I reading this right?

> One huge pet peeve I have the with current build setup though is all the generated headers and object files are placed in the same directory as source randomly breaking the build when building both Linux and Windows from the same repo.

Generated headers and vm file may cause a bit of a problem, but it shouldn't be impossible to fix.  I've created #24 for it.

**Comment by siddhesh** [comment]
> How about tup？？
> http://gittup.org/tup/

It looks like it will require a complete rework for little gain. That may not be a worthwhile effort.

**Comment by stone-wind** [comment]
how about xmake? xmake is a cross-platform build utility based on lua. it is a little interesting.

**Comment by siddhesh** [comment]
Does it solve the problems that we want to solve (see above) by changing the build system?

**Comment by CapsAdmin** [comment]
I don't think it makes sense to argue the complexity of a build system since batch and shell are also very complex. They are well understood and readily available though which I think is the main pro. 

The current build system looks like it's 1500~lines of hand written batch and make code. A lot of that is similar looking batch code for game consoles.

Personally I would make use of "minilua" that is used in dynasm as a replacement for make/shell and batch.

**Comment by waruqi** [comment]
If I contribute a pr to help you add xmake build support, would you consider switching to the xmake build system?  

xmake is a cross-platform build utility based on luajit. https://github.com/xmake-io/xmake

example: https://github.com/tboox/tbox/blob/master/src/tbox/xmake.lua

**Comment by siddhesh** [comment]
The problems with the current build system, as highlighted above are:

- Unify build systems for Windows and *nix
- Allow building into a separate build directory

While build system unification is a bit of a problem with make, building into a separate directory should be easy to fix.  What this means is that right now there's not a lot to gain by changing build systems.

I've kept this issue open in case there are other problems people can think of that make cannot do satisfactorily, that some other build system can.  So in essence, I'm looking for problems to solve than solutions.

**Comment by waruqi** [comment]
I written a xmake.lua to use [xmake](https://xmake.io) to build moonjit.  

It support for android/ios.

https://github.com/xmake-io/xmake-repo/blob/master/packages/m/moonjit/port/xmake.lua
