### ISSUE TITLE
Windows documentation cleanup

### ISSUE THREAD

**Issue by siddhesh** [moonjit/moonjit#29]
The instructions to build on Windows seem outdated, specifically the links to download toolsets since they seem to be aimed at XP/Vista/7 era products.  I do not have access to Windows systems to verify the instructions and would appreciate help with it.

**Comment by joe-92** [comment]
I'll look into it tomorrow. @siddhesh, do you have an idea about issue #52? Maybe we should bump the minimal required MSVC Version to 2015 which also would remove some ifdef's from the codebase, e.g. https://github.com/moonjit/moonjit/blob/4dba12d16f2eb455198821da522e99554e01d97d/src/lj_def.h#L11 or https://github.com/moonjit/moonjit/blob/4dba12d16f2eb455198821da522e99554e01d97d/src/lj_arch.h#L588

**Comment by siddhesh** [comment]
I don't have a sense for what Windows developers typically use, i.e. if 2015 is too old for a majority of them or whether it is normal to stick to 5-10 year old development environments.  I'll trust your judgment on this.  If you post a PR to drop support for older VS, please document it as such in INSTALL.md and mark this issue and #52 as resolved with it.

**Comment by fsfod** [comment]
It doesn't effect my personally any more but people do tend to get stuck with ancient VS versions because upgrade costs. It would be nice not to worry about declaring variables the C89 way always at the top of the function that only got supported in i think VS2013. Travisci is bad for this as well since it comes ancient versions of GGC in its LTS ubuntu [example of the problem](https://github.com/Kong/openresty-patches/pull/54).

**Comment by joe-92** [comment]
I updated the documentation and created a pull request #64 . I'm unsure what to do about supporting older Visual Studio (or even gcc) versions. Should we open a separate issue to discuss this topic?

**Comment by siddhesh** [comment]
I like the weak recommendation in #64, I understand the "being stuck with older environments" bit but I don't see the point of adding cruft to 'fix' bugs in the C library.  #64 is good enough to mark this as resolved.

**Comment by joe-92** [comment]
I looked through the source code to find all 'workarounds' for VS. I think some of them could be dropped if bumping the required version number.

`log2` and `exp2` are (at least since VS 2015) part of the CRT (see https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/exp2-exp2f-exp2l and https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/log2-log2f-log2l):
https://github.com/moonjit/moonjit/blob/a77937cc6c59ff21d684837a14ce0ea51284f50b/src/lj_arch.h#L587-L593

Also `stdint.h` and `stddef.h` are now included (also at least since VS 2015, see https://docs.microsoft.com/en-us/cpp/c-runtime-library/standard-types):
https://github.com/moonjit/moonjit/blob/a77937cc6c59ff21d684837a14ce0ea51284f50b/src/lj_def.h#L11-L42

The two statements `_MSC_VER >= 1400` could be simplified:
https://github.com/moonjit/moonjit/blob/a77937cc6c59ff21d684837a14ce0ea51284f50b/src/lib_io.c#L328-L347

There is a workaround for VS in `lj_num2u64`. Has anyone an explanation and knows if the code is still correct since the commit 454bea87cff4ff3cd2fd9ae34a3718dd200ce0fb?
https://github.com/moonjit/moonjit/blob/a77937cc6c59ff21d684837a14ce0ea51284f50b/src/lj_obj.h#L950-L964

And two more bugfixes:
https://github.com/moonjit/moonjit/blob/a77937cc6c59ff21d684837a14ce0ea51284f50b/src/lj_cdata.c#L131-L141
https://github.com/moonjit/moonjit/blob/a77937cc6c59ff21d684837a14ce0ea51284f50b/src/lj_opt_fold.c#L842-L853

And another thing I don't fully understand (yet):
https://github.com/moonjit/moonjit/blob/a77937cc6c59ff21d684837a14ce0ea51284f50b/src/lj_lib.h#L62-L69

**Comment by siddhesh** [comment]
> There is a workaround for VS in lj_num2u64. Has anyone an explanation and knows if the code is still correct since the commit 454bea8?

~~That is likely incorrect but I didn't bother with it back then.  FWIW, even the x86 JIT doesn't handle undefined unsigned to float conversions well yet.~~

EDIT: Scratch that, it does look correct.  For positive integral values beyond range, it wraps around by subtracting UINT64_MAX.  It looks weird (and that might be the MSVC quirk), but should work.

**Comment by siddhesh** [comment]
Overall though, lets not bump versions yet.  We can revisit that for v2.3.

**Comment by XVilka** [comment]
See also https://github.com/LuaJIT/LuaJIT/commit/c6c6e3b416635a528a711ed1986b054287a7c491 and https://github.com/LuaJIT/LuaJIT/commit/3ece3a3e3a448ecc54e317fd5743d1f4c19db28b

**Comment by siddhesh** [comment]
> See also [LuaJIT@c6c6e3b](https://github.com/LuaJIT/LuaJIT/commit/c6c6e3b416635a528a711ed1986b054287a7c491) and [LuaJIT@3ece3a3](https://github.com/LuaJIT/LuaJIT/commit/3ece3a3e3a448ecc54e317fd5743d1f4c19db28b)

Thanks, I've incorporated those patches into our tree.  Please note that I am not updating doc.luajit, only the markdown docs that I've ported.  If someone wants to keep doc.luajit updated for whatever reason they're free to post PRs (and I'll accept too!) but it's not a focus for me.

Closing this now since the primary purpose is served.  We will revisit the version bump in future if needed.
