### ISSUE TITLE
Compiling for bare-metal ARM

### ISSUE THREAD

**Issue by odevices** [moonjit/moonjit#31]
Is this possible with moonjit?  

I am already embedding Lua in my bare-metal firmware application on a Cortex-A8 and it would be great if I could get moonjit in there instead.

My compile flags are:
-mcpu=cortex-a8 -mtune=cortex-a8 -march=armv7-a -marm -mfloat-abi=hard -mfpu=neon

**Comment by siddhesh** [comment]
I know it builds for armv7 HF, but I haven't had a chance to use it on bare metal.  Have you tried using the cross-build instructions in in [INSTALL.md](https://github.com/moonjit/moonjit/blob/master/INSTALL.md) but with a bare-metal toolchain setup?  moonjit doesn't have any exotic requirements and should build just fine even with a bare metal toolchain.

Please let me know if it works, or if you had to do something extra to get it working.  I'd love to have a section on bare metal builds in [INSTALL.md](https://github.com/moonjit/moonjit/blob/master/INSTALL.md).

**Comment by odevices** [comment]
I'll see what I can come up with but I expect I will hit a big snag when it comes to dlopen/dlsym dependencies, right?

**Comment by siddhesh** [comment]
dlopen shouldn't cause problems; AFAICT it's only really used via FFI in moonjit and since you intend to use it as a replacement for Lua, FFI shouldn't matter.

In any case moonjit checks for presence of dlopen and fails gracefully if the target (i.e. the C library you use to build for bare metal) doesn't support it.  So it really depends on the libc you use.

I look forward to the results of your experiment.

**Comment by siddhesh** [comment]
Closing this as it is a general discussion/question.  If there are specific issues with bare metal, please feel free to raise Issues/PRs (latter preferred of course!) for the same.
