### ISSUE TITLE
update jit version check in src/jit/*.lua

### ISSUE THREAD

**Issue by joe-92** [moonjit/moonjit#32]
Hi siddhesh, thanks again for your work! Unfortunately a bug slipped in at 2.1.1 release: the version checks in the files [src/jit/bc.lua](https://github.com/moonjit/moonjit/blob/v2.1/src/jit/bc.lua#L44), [src/jit/bcsave.lua](https://github.com/moonjit/moonjit/blob/v2.1/src/jit/bcsave.lua#L14), [src/jit/dump.lua](https://github.com/moonjit/moonjit/blob/v2.1/src/jit/dump.lua#L58), [src/jit/p.lua](https://github.com/moonjit/moonjit/blob/v2.1/src/jit/p.lua#L44) and [src/jit/v.lua](https://github.com/moonjit/moonjit/blob/v2.1/src/jit/v.lua#L62) have not been updated. I would create a pull request, but I don't know if I should bump the version number to 2.1.2 😃

**Comment by siddhesh** [comment]
Yikes, I knew I would miss out on something in a hurry.  Please create a PR for 2.1.1 for now; that way at least people looking for a quick fix can backport that patch.

We need to figure out a way to document the release process clearly too so that it is clear to anyone doing it for the first time.

I'll bump everything to 2.1.2 next week with maybe more one or more fixes tagged along with it.
