### ISSUE TITLE
Push into the distributions as LuaJIT successor

### ISSUE THREAD

**Issue by XVilka** [moonjit/moonjit#58]
Into all Linux distributions where LuaJIT was packaged:

https://repology.org/project/luajit/versions

**Comment by TSnake41** [comment]
I'm not sure that it will be accepted (at least now).
Well, LuaJIT has not be updated since months but it's still solid and working as expected (most of the time at least)

First, I will see it as a derivate project (like gitea and gogs) and maybe in the future, if it still follow the same philosophy, be considered as the "successor" by the community.

If you don't change LuaJIT too much (keep the same build system, no dropped platforms, do not add invasive stuff, same/similar API, ...) then I don't see why I would not consider MoonJIT as the LuaJIT successor.

**Comment by hippi777** [comment]
hi there! :)

im not enough familiar with the packaging related stuffs, but this looks like a duty for `/etc/alternatives`

otherwise probably gitea and gogs were about the same, but i dunno them, and if not, then the mysql vs mariadb case could be possibly a good example and starting point for making lj and mj coexist (i dunno if thats anything different than just utilizing `/etc/alternatives`) as those can be kinda invisibly exchanged, and i can call for mysql when only mariadb is installed

bests! :)

**Comment by siddhesh** [comment]
> I'm not sure that it will be accepted (at least now).
> Well, LuaJIT has not be updated since months but it's still solid and working as expected (most of the time at least)
> 

The original intent of the project (which stays intact) was in fact to supply updates to distributions and keep them updated.  If you look at the Fedora luajit package (which I maintain) for example it has patches from my tree, which eventually became moonjit.

All distribution maintainers I spoke to (Debian, Fedora (i.e. the other co-maintainer, not myself ;)), OpenSuse, Arch) before actually making this hard fork agreed to replace luajit in one form or the other, i.e. either by just using the moonjit tarball and keeping the luajit name as the package (Debian, Fedora) or by using the obsoletes/conflicts mechanism to replace luajit with moonjit.

If you're interested in a specific distribution, I'd suggest filing a bug report in that distribution to accelerate the process.  I had intended to drop all the maintainers a quick email to let them know of the 2.1.2 release, but I haven't had the time over the last week.  I hope to find some time to do that tomorrow.

> First, I will see it as a derivate project (like gitea and gogs) and maybe in the future, if it still follow the same philosophy, be considered as the "successor" by the community.
> 
> If you don't change LuaJIT too much (keep the same build system, no dropped platforms, do not add invasive stuff, same/similar API, ...) then I don't see why I would not consider MoonJIT as the LuaJIT successor.

We are definitely not dropping platforms and we are not extending the lua API in incompatible ways (with the exception of openresty extensions, most of which will make it under special compiler flags so that the project can be a drop-in replacement for openresty/luajit2) so in many ways anything the project does that does not adhere to this is a bug and should be reported as such.

**Comment by siddhesh** [comment]
Closing this, since the issue of adding to distributions is really something that should be tracked in distribution bug trackers and not here.
