### ISSUE TITLE
LuaJIT/LuaJIT dropped ppc support

### ISSUE THREAD

**Issue by siddhesh** [moonjit/moonjit#87]
LuaJIT/LuaJIT dropped support for ppc recently:

```
commit 981ec8d2aac5cac76bdedd4015b6d32447b29597
Author: Mike Pall <mike>
Date:   Mon Jan 20 22:56:47 2020 +0100

    Remove support for de-facto dead archs.
```

I had to fix ppc64be bugs for some Debian folks in the past so I'm assuming that the port is still in use.  I have not cherry-picked that patch for that reason but would like to hear comments from people who may have a stake in this.  The question here is, is it OK to just drop ppc/ppc64be support or are those architectures still considered active?  I know they're considered active in glibc for instance, but we have far greater backward compatibility constraints.

@seth-priya , @walbon , any comments?

**Comment by seth-priya** [comment]
@siddhesh sorry for the slow response, I am just getting back after a couple of weeks. So, yes ppc64le (and I would believe the same for ppc64) are very much in use. 

In fact, we (in the ppc64le world) are hitting more and more open source packages that have either a direct dependency on luajit / luajit2 or are dependent on it via the openresty path, so this is most certainly in use and important for us.

This is one of those that come repeatedly (for ppc64le)
https://github.com/kubernetes/ingress-nginx

https://github.com/draios/sysdig
is another one where my team recently pushed a change up-stream to use moonjit instead of luajit for ppc64le https://github.com/draios/sysdig/blob/dev/CMakeLists.txt#L165
sysdig in turn is consumed by https://github.com/falcosecurity/falco and is used in the IBM Public cloud

Overall ppc64le is what my team's mission is focused on, so it and continued support is moonjit is certainly important for us.

@gerrith3 for any additional comments, thoughts and an FYI here.

**Comment by seth-priya** [comment]
@clnperez FYI

**Comment by hippi777** [comment]
hi there! :) 

ive seen that change, but i didnt really understand its reason and scope, but actually i would care about this one:
https://www.powerpc-notebook.org

i think its big endian, and seems to be like the only really free notebook alternative, other than the ancient thinkpads, that still have closed source hardware, but at least those have deblobbed firmware without "nsa backdoor" (coreboot folks would argue, that its a "frontdoor", cuz its documented, but whatever)... btw its still just the (near?) future, and i know its openhw, but i dunno about its fw. even the risc-v boards of sifive require blobs, so freedomwise, maybe this is the best future-wise, but im not really into the world of power architecture, so sorry in case if i say anything wrong here... i dont even know if ppc belongs under openpower or not, and if its just a step forward from that in case if not...

so actually my question is the range of that change, and if this ppc notebook is affected or not? ive seen only a few lines of change, and i believe that Mike knows what he does, but now i dunno whats going on...

many thx for any info on this! :)

**Comment by gerrith3** [comment]
Power ended support for Big Endian in Linux (i.e. since ~2015 none of the major distros support a big-endian Linux).  Mac ended support in MacOS Lion in 2011 and quit shipping Power based laptops in ~2006.  The currently released Power ISA is capable of running in either big or little endian mode; however, for data compatibility little endian is the "smart" choice due to compatibility.  Only AIX (and probably System I) use Big Endian today and despite the maturity of AIX and experience, porting open source to that platform still requires a bit of additional effort.
In other words, I would propose that the primary focus, e.g. shipping othardware with supported OS, focus on Linux on Little Endian, and enabling LuaJit for that environment.  I'm not down-voting the support for the page you indicated above - only indicating that there are an enormous number of high end customers that use Linux on Power and are hoping for support for LuaJit ASAP in commercial environments.  The demand is often hidden behind a few IBMers (many on my team) who make requests like this.  But we have hundreds of live enterprise systems running high end commercial workloads that can use this capability today.  OpenPower is another forum with new hardware like the Raptor that is Power based and little endian - I can't speak to the Raptor's customer base but they are also depending on having a full open source ecosystem available and that is probably going to be a more successful path for wide-spread adoption than the powerpc-notebook effort (again, not trying to diminish it - just trying to show the relatively higher priority of little endian Linux!).  Thanks!!!

**Comment by hippi777** [comment]
thx! :)

im not that much near to that project, and actually im puzzled around this topic with a lotsa fragments of info in my head from here and there (coreboot ml, purism forum, recently seen something related on phoronix about risc-v and openpower, and whatever...), and none of the related projects is perfect, but the phoronix post and its comments made me realize that openpower is maybe an even more promising thing than risc-v, so im even more puzzled about that, as im a total newbie around the power architecture... :D 

however, just to confirm me, actually are we talking about complete platform drop? it smells, as its still a thing, and if u say so, then Mike should know it better than me that its still in active use, and i think its really not like atari and c64, while ive never seen around luaverse anyone who used it on xbox, but maybe i dunno enough about that as well :D (btw its not an important thing to me anyhow, i just brought that up for a possibly poor example). and if thats the case, do u know about the reason of dropping it on the 1st place? i only know that it was said to be ancient, so 1st, ive thought that its only about a partial drop, like how uve said big endian is dying out, so that seems to be legit, while ur talking about little endian... btw if u are right (y not?) then u could talk with Mike on the 1st place, as i think it doesnt require much maintenance as it already exists, while i think the rest of the codebase wont benefit that much from dropping it, maybe further development benefits from that as its not needed to be ported to one more platform, but in that case Mike could keep it as long as anybody takes the maintenance of it, and in the worst case, he can still say that the related bits are not blessed by him, and he doesnt take the responsibility for the users of it...

but whatever, im just thinking out loud without enough background knowledge :D (sorry if ive said anything dumb :D )

bests! :)

**Comment by gerrith3** [comment]
OpenPower has a ton of potential in much of the high end AI and cognitive workloads, and is also a workload server for lots of applications around data management, application development, etc.  I haven't seen the Phoronix port but Michael over there usually does a lot of research on his posts.  And, given your summary, I would definitely agree.  Intel, Arm, Power, Z, are probably the primary chipsets out there today, but it is always a big market and lots of "niches" (like Z runs 95% of the big banks in the world but doesn't have a desktop or laptop offering, hence a rather big niche).

Big endian Linux was dropped because the porting hurdle (porting all 1+ million active github projects, for instance) was just never going to happen.  Porting all to little endian dropped the bar substantially in porting costs, as well as simplified integration with Intel servers (which are also little endian, hence all data generated and stored is typically little endian).  The new Power chip actually allows both big endian and little endian, and even allows VMs to run in little or big endian on the same server.  However, strategically, all investment from IBM is in little endian for Linux on Power.
As far as maintenance, my team pushes for integration into a CI environment - Travis Ci is free for Power open source projects, for instance, and we have places to integrate Jenkins or a raw VM into a CI environment thorugh Oregon State University's Open Source Lab (OSU OSL).  Thus, maintenance should wind up being very easy, and 95+% of things that break on Power also break on Intel.  So, keeping the code in will make some people very happy, without introducing much (if any) of a drain on the project maintainers - especially once a CI environment is properly set up and running.

**Comment by hippi777** [comment]
thx for all the info! :)
ive found the link for u: https://www.phoronix.com/scan.php?page=news_item&px=RISC-V-Not-All-Open-Yet

**Comment by clnperez** [comment]
It looks like that commit dropped support for ppc -- which was, IIUC, a 32-bit BE support. Since luajit never had 64-bit ppc64le support, I'm not sure we ... care about that? @gerrith3 @seth-priya?

**Comment by siddhesh** [comment]
> It looks like that commit dropped support for ppc -- which was, IIUC, a 32-bit BE support. Since luajit never had 64-bit ppc64le support, I'm not sure we ... care about that? @gerrith3 @seth-priya?

Nope, it removes ppc64be, only minimally so that it throws an error at build time.  There's literally this line that gets added in the change:

```
+#error "No support for PPC64"
```

**Comment by siddhesh** [comment]
Thanks for your feedback everyone.  FWIW, I don't plan to drop or add architectures based on LuaJIT/LuaJIT because I don't have visibility into what thought goes into that decision making.  As long as there are volunteers from IBM helping with maintaining the Power bits in moonjit I'll happily keep it in.

That is also why I explicitly wanted feedback from y'all.  If any architecture bits need to be removed because IBM does not support them anymore, please feel free to propose patches to do that for moonjit.

**Comment by hippi777** [comment]
i just came across the purism forum thread that i mentioned above in case of interest:
https://forums.puri.sm/t/possibility-of-a-purism-power9-or-risc-v-system-within-near-future/4445

**Comment by XVilka** [comment]
You might consider to ping IBM [BountySource](https://www.bountysource.com/) team:
- https://www.bountysource.com/teams/ibm/issue_suggestions/new
- https://www.bountysource.com/teams/ibm

As you can see, they tend to support PowerPC and SystemZ in a range of open source projects. They might be interested in MoonJIT as well.

**Comment by siddhesh** [comment]
Closing this discussion; ppc support continues to live in moonjit.
