### ISSUE TITLE
std functions rewritten in Lua shouldn't trigger the debug line hook internally

### ISSUE THREAD

**Issue by hishamhm** [moonjit/moonjit#93]
This issue refers to the LuaJIT issue LuaJIT/LuaJIT#516.

The implementation of `table.remove` triggers the debug hook multiple times. This leaks to the language user the fact that this function was internally reimplemented from C to Lua. This has caused performance regressions to the point of making luacov unusable in some cases.

Mike closed this as wontfix in LuaJIT. 

I understand this may be tricky to implement an efficient fix (my first naive assumption [doesn't work](https://github.com/LuaJIT/LuaJIT/issues/516#issuecomment-565375348)).

**Comment by siddhesh** [comment]
I'm inclined to revert to the C implementation until we can figure out a fix.  AFAICT there's nothing in particular that the lua implementation of `table.remove` fixes.

**Comment by hishamhm** [comment]
Sounds fair to me, given the other comments in the original thread.

I haven't checked if any other standard library functions that were rewritten in Lua exhibit this same behavior of looping and triggering multiple debug line hooks.

**Comment by siddhesh** [comment]
I ran out of time to do anything useful with this today, but wanted to dump some thoughts before I leave it so that I don't have to start over the next time.

A lot of the table library ops are implemented in lua, so if the intent is to never have debug hook execute for lines inside std functions, we would have to disable hookf calling upon entering these functions and reenable upon exit.

I've never looked at the bcgen stuff before, so I'll have to figure out how it stores the bytecode and retrieves it later.  Perhaps the easiest thing would be to have a special bc op that twiddles the debug hook.

**Comment by hishamhm** [comment]
> the intent is to never have debug hook execute for lines inside std functions

I believe that's the intent, otherwise the expected number of debug calls in a Lua vs LuaJIT run changes by the big-O factor of those functions

> Perhaps the easiest thing would be to have a special bc op that twiddles the debug hook.

If that's a performance hit, then perhaps even considering having "debug" and "release" modes that change whether that op is emitted? On second thought, could even use `-joff` as that mode setting, since the debug library basically doesn't work reliably on JIT mode anyway, and that's already the recommendation for using tools that rely on the debug library behavior such as luacov.
