### ISSUE TITLE
[Feature Proposal] setlen builtin

### ISSUE THREAD

**Issue by mnemnion** [moonjit/moonjit#94]
Lua's behavior around 'sparse' tables can be surprising.  While mainline Lua has a solution incoming, in the form of `undef`, I have a proposal which I consider to be more in keeping with the LuaJIT philosophy.

Some exposition: it's possible to have `nil` in a table under some circumstances:

```lua
-- this returns 4
return #{1, 2, nil, 4}
```

While in other cases, this ends the 'array portion' of the table:

```lua
-- this returns 1
return #{1, nil, nil, nil, 5, nil, 7}
```

However! Consider this:
```lua
return #pack(1, nil, nil, nil, 5, nil, 7)
```

It returns `7`! `pack` is able to set the value of `#` to the situationally-correct value, `7.` 

It also sets `.n = 7`. But that's a convenience! Consider:

```lua
tab = pack(1, nil, nil, nil, 5, nil, 7)
tab.n = nil
return unpack(tab)
```

Returns all 7 values of tab, `nil`s and all.

It fails in the other direction, as well:

```lua
return unpack {1, nil, nil, nil, 5, nil, 7, n=7}
```

Only returns `1`.

### Proposal: setlen

I propose a `setlen` built-in primitive, which would allow this:

```lua
return #setlen({1,nil,nil,nil,5,nil,7}, 7)
```

To equal 7,  as in `pack`.

### New Semantics: ipairs, table.insert?, table.remove?

To gain consistency, this would require new semantics for `ipairs`, and arguably, for `table.insert`, and `table.remove`.

I will argue that any code this breaks, was already broken. Consider:

```lua
collect = {}
for i, v in ipairs {1,2,nil,4} do
     collect[i] = v
end
return #collect
```

Returns `2`, because `ipairs` breaks on the `nil` value, even though `#{1,2,nil,4}` is `4`.  `ipairs` would therefore be modified to return the index `3` and a `nil` value, up to the value of `#`.

Similarly:

```lua
tab = {1, 2, nil, "foo"} -- #tab is 4
table.insert(tab, 3, "uh-oh")
-- we have the correct contents:
-- {1, 2, "uh-oh", nil, "foo"}
-- but #tab is now 3!
```

`insert` and `remove` are a harder case, and it's maybe better to leave this behavior in place and require the user to specify when they want a table to remain sparse. 

Here's the definition of a table struct:

```c
typedef struct GCtab {
  GCHeader;
  uint8_t nomm;		/* Negative cache for fast metamethods. */
  int8_t colo;		/* Array colocation. */
  MRef array;		/* Array part. */
  GCRef gclist;
  GCRef metatable;	/* Must be at same offset in GCudata. */
  MRef node;		/* Hash part. */
  uint32_t asize;	/* Size of array part (keys [0, asize-1]). */
  uint32_t hmask;	/* Hash part mask (size of hash part - 1). */
#if LJ_GC64
  MRef freetop;		/* Top of free elements. */
#endif
} GCtab;
```

So what `pack` is clearly doing is allocating a larger `array` and setting `asize` accordingly, while `ipairs` (I suspect) is using `asize` for bounds checking but aborting if it finds a `nil` reference. 

The proposal for `setlen` is to follow `pack` in expanding the array portion and adjusting `asize` accordingly, and changing the behavior of `ipairs` to use `asize` to decide when to stop iteration, congruent with the existing behavior of `unpack`.

What `table.insert` and `table.remove` apparently do, is insert and remove values, regardless of whether they're in the hash or the array portion, at the given index, then let the Lua runtime decide how to reallocate things.  Modifying this would be difficult, and hard to reason about. 

The proposed solution is somewhat unsatisfying: if the user invokes `setlen`, then `inserts` a value, and invokes `setlen` again, this will trigger a flurry of copying, and I suspect the JIT won't like that. 

I still consider it the better solution: the workaround is to do the insertion in a loop, use `setlen` once at the end, and leave the table alone. I would guess this matches most of the cases where invoking `setlen` would be helpful.

The tricky part is that `pack` builds a `GCTab` from scratch, and `setlen` would have to have logic to move values out of the hash portion of the table, even if those values were `nil`, a different behavior from the stock function for adjusting tables on mutation.  And if we had this logic, it could be used by `insert` and `remove` as well.  

I think this would be at risk of changing the semantics of non-broken code. There's surely something which relies on what `ipairs` is doing, somewhere; any semantic change will break something. But I guarantee there's code that relies on `remove` in particular adjusting the array portion, and I don't think it's worth breaking that.

Thoughts?

**Comment by hippi777** [comment]
hi there! :)

changing the semantics is an explicit non-goal here if im right (drop in lj replacement). this means a slightly distinct language, while its still possible to make universal codes, but i think it would hurt many ppl out there...

also, i think it wouldnt be beneficial to mj, as that would keep away adopters, while the recent "lua version census" (see lua-l) brought up that mj isnt really widely adopted by the community so far now. making it to be optional would require the constant maintenance of it (or better said: to not deprecate it) if anybody start to rely on it, while its hard to clean up if it will be included and then dropped... but thats upon Siddhesh...

lj is currently in a state where it can remain a drop in replacement for 5.1 with extras, it can slowly leave behind puc lua, or follow it up, while Mike wanna keep that stable point if im right, saying that based on the intentional keeping of the 5.1 api, thats the reason to not catch up with puc lua, so i think u dont have much good chances there as well.

puc lua is already in a hard position with ppl writing their codes basically from 5.1-5.4, and to not kill the ecosystem entirely, they must move forward really much carefully and wisely. a backward incompatible 6.0 will be even possibly a black day, where they may even lose their control over lua, as luajit, with all its huge selling points will be probably around this state and get optimizations and polishing mostly, and the whole ecosystem of lua will remain in the 5.x line, while its not python to convince the crowd to jump, even if a remarkable amount of users would jump, and even if i think that a 6.0 will be way more compatible than what python did when jumped to 3.x... but i didnt want to say this, but that i think its not a wise thing to ask them, cuz of the previous reasons (that are probably painted in a more creepy fashion than its necessary), while that would be the right entry point imho to start a change.

i believe the best chances are at forks that went far on the road of pimping up the language...

sorry for being distressing, but all the bests to u! :)

**Comment by mnemnion** [comment]
Adding `setlen` can't really be considered a semantic change. It would be quite possible to write it as a small C library and `require` it, making it no different from any other function: if a program doesn't have it, then it can't use it.  No different from `coroutine.clone` in that respect.

Changing the behavior of `ipairs` is a semantic change, yes, but a very small one that many users would welcome. It's also the least important part of this change, it's easy to use a numeric for loop or override the `__ipairs` metamethod to get that functionality.

I could be wrong about the "essence" of this project, I believe the goal is to extend LuaJIT without reference to what PUC Lua is doing with the language.  Certainly if they decided to use `_ENV` I would have no use for this fork.  Also, an important point, it is *ABI* stability, not *API* stability, with 5.1, that Mike Pall has indicated he doesn't want to break.

This would change nothing in the header files; ABI stability would remain intact.

**Comment by hippi777** [comment]
yep, i was about ipairs with the semantic change, and actually i just reread ur 1st message and i had to realize that uve found 2 bugs! :D i just checked out both the 5.1 and 5.2 refmans, as well as the extensions page of luajit docs, and both `table.pack()` and `table.insert()` misbehaves according to those. :D i dont have 5.2 compat enabled, so i wrote `table.pack=table.pack or function() return {n=select('#', ...), ...} end` (that is also good to have an engine-independent base) and it behaves just how the refman says so, and i have no other engines at hand currently (i could, but currently im "living" on a 8g pendrive after a hdd crash, and its a real pain to install anything on it, that would be the toolset to compile other engines, but if it would be really needed, then i could :D ) to check out the behavior for `table.insert()` both on 5.2 and luajit with 5.2 compat enabled, but the manual says that it should shift towards the rest of the array part that is provided to the users, while luajit messing up the real array part that must be only an implementation detail. the length operator must be only used on tables without holes, as thats again an implementation detail that it uses a logarithmic search to find the last element. so `#{1,2,nil,4,nil,nil,nil,8,nil,nil,nil,nil,nil,nil,nil,16}` will always give `16`, but this should be not relied upon, as its an implementation detail, that wont change on the side of lua, as 5.1 reached its final state, but luajit may still change. at least i think that that behavior is the case on all of the engines, as the logarithmic search is the best speedwise, and also, the lua refman says that the operator has an undefined behavior in tables with "holes" right because of this optimization, however i dunno the puc implementation, but luajit uses exponents of 2 to make the array part, and this implementation detail leaks here, as things rely upon that, while they shouldnt, or better said, they should handle it correctly...

@siddhesh @MikePall, could either of u confirm the above? the rest isnt that much important, thx! :)

the `n` filed is in use, and is accepted, as long as its usage reaches, so in favor to that, i think it should be fixed, instead of making it a subject of changing... the `ipairs` can be turned into a numeric `for` in case of need, just as uve said, and `n` can be used just for that purpose without making a special accessor to a hidden value, so i would even prefer that way, maybe just like the way how u dislikes `_ENV` if ur about its "magic", and not about compatibility... btw in the latter case i think it can be implemented both ways via the `debug` library and metatables (im not sure), where the `debug` is innocent and reliable even in sandboxes, where u can rely on it at will, without problems, as long as u hide its raw form from the users...

about moonjit, Siddhesh is the package maintainer of luajit, and while Mike took his really long "holidays", he wanted to make a drop-in replacement for luajit with merging the pending pr's, but later on, he took an another flagship that i know about, and that is to keep the lj forks as near as possible, so he merged the openresty modifications, that can be en-/disabled at will, just like the 5.2 compat modules, so thats also a thing that is achievable without losing compatibility, so i clearly believe that its an explicit project goal to keep the compatibility, and also, thats my personal opinion as well.

about luajit, its also stated that it wants to stay api compatible with lua, not just abi, the latter is even a 2ndary goal, just cuz its intended to be a lua 5.1 drop-in replacement, probably cuz of gaining users that shouldnt be afraid of incompatibility, but i say 2ndary, cuz ffi is preferable over the c api, so the abi compatibility could be even dropped, just how Luke at raptorjit considered to drop it back in time, maybe like a year ago...(?) and actually luajit has compatible extensions only, otherwise it wouldnt/couldnt be a real drop-in replacement.

disagreements are welcome, as i didnt make my homework like how ive just said, and as im not the owner of nether of these projects, and as sharing ideas is always fine. :) otherwise i really think that fixing of those issues is the golden path, but only in case if im right about them :D 

bests! :)

**Comment by siddhesh** [comment]
[apologies for the silence, was tied up in other projects]

@mnemnion thank you for the detailed request. The goal of the moonjit project is to provide a way forward for LuaJIT users by attempting to converge paths with various forks, including upstream Lua.

So in that respect, I had a few questions:

* Can you share a reference for the lua `undef` implementation to fix the sparse tables issue?  Do they make the behaviour consistent (i.e. treat them like arrays all the time and return up to `nil`) and then use a new `undef` keyword to mark elements in the middle as `nil` without affecting the length property?  It would be nice to get a sense of what they're doing in Lua.

* Were you able to discuss this approach with PUC Lua?  As I mentioned, converging with PUC Lua (and other popular lua implementations/forks) is an explicit goal.  As a result, I'd like to make sure that any extensions we implement in moonjit either (1) are on the roadmap for PUC lua and there is agreement on semantics or (2) is not going to be in PUC Lua and they won't add anything in the same namespace that confuses with whatever API we add.

* Finally, can you elaborate on why setlen is a more LuaJIT-like solution to the problem instead of `undef`?  I'm afraid I am not familiar with the philosophical history (and differences) of Lua and LuaJIT; my interest in luajit/moonjit is primarily as a toolchain hacker interested in learning, understanding and extending the techniques implemented in luajit and my background in the Lua language itself is relatively sparse.

**Comment by mnemnion** [comment]
The discussion of `undef` was on the Lua mailing list, but perusing the 5.4 release notes, the change didn't make it into that point release.  So it's unclear if it ever will.

However, I think the idea was the opposite: any undefined value would return `undef` for that key, so that one could explicitly put `nil` into the array portion of a table and `#` would adjust accordingly.  

It's not a bad idea, on the face of it, but it complicates the language. Personally, I have very bad associations with `undefined` thanks to JavaScript. Normally when Lua and JS both do something, the Lua version is without the weird warts and edge cases that the JS version is burdened with, so I'm neutral on the subject. 

You are, of course, more than welcome to do whatever you please with moonjit, since it's your project. If you do decide to implement `_ENV` instead of `setfenv/getfenv`, I won't be using moonjit. I think PUC Lua made a huge mistake there. I also have limited interest in adding a bunch of bitops and integer support, since the ffi offers a complete solution there with cdata and the `bit` package. 

I think the LuaJIT community should go in its own direction, emphasizing the stability of the fundamental 5.1 language. I'd welcome implementations of the new functions in >= 5.2, but have negative interest in the semantic change to environments and the syntactic sugars for bitops. 

What I'm keenly interested in: the work RaptorJIT has done to break the 4GB program size limitation, but ported to all the platforms LuaJIT supports. The same with respect to their code which trace-optimizes `pairs`, and any other tracing enhancements they manage to write. Hyperblock scheduling and the quad-color garbage collector, presuming there's anyone but Mike Pall who can actually implement them performantly. Bug fixes, additional trace optimizations, and more control over the low-level aspects of the engine from the Lua side.

Which is why I think `setlen` is a more "LuaJIT-flavored" solution. There's an array portion of the table struct, and from the C side, it's quite tractable to put `nil`s in it, with the result that on the Lua side `#` will report a larger value.  `setlen` would allow scripts to do this from the Lua side, without changing the semantics of the language; the more I think about `ipairs`, the less I care that it short-circuits on `nil`. 

The documentation for `ipairs` says:


> Returns three values: an iterator function, the table t, and 0, so that the construction
> 
>      for i,v in ipairs(t) do body end
> will iterate over the pairs (1,t[1]), (2,t[2]), ···, up to the first integer key absent from the table.

Which is accurate.  While I would prefer that it iterate up to the value of the `#` operator, that would constitute a semantic change, and those should be contemplated very carefully. 

`setlen` would not; no program that doesn't use it would change, any program that happens to have a `setlen` function would keep using that function in whatever context it was defined in, and so on.
